name: ffparaim
channels:
  - conda-forge
dependencies:
  - openff-toolkit
  - pip
  - pip:
    - git+https://github.com/theochem/iodata.git
    - git+https://github.com/theochem/grid.git
    - git+https://github.com/theochem/gbasis.git
    - git+https://github.com/theochem/denspart.git

